plants/urls.py
from . import views
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "plants"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("pricing", views.pricing, name="pricing"),
    path("support", views.support, name="support"),
    path("careers", views.careers, name="careers"),
    path("videos", views.videos, name="videos"),
    path(route='faqs', view=views.faqs, name='faqs'),
    path('accounts/', include('accounts.urls')),
    path('predictor/', include('predictor.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "predictor"

urlpatterns = [
    path("select_plant", views.selectPlant, name="select_plant"),
    path("upload_image/<str:plant_name>",
         views.uploadImage, name="upload_image"),
    # path("get_single_prediction/<int:id>",
    #      views.getSinglePrediction, name="get_single_prediction"),
    path("get_predictions/<str:plant_name>", views.getPredictions, name="get_predictions"),
    path("delete_image/<str:plant_name>/<int:id>", views.deleteImage, name="delete_image")
]

predictor/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Image(models.Model):
    name = models.CharField(max_length=255, default="image")
    image = models.FileField(upload_to='images/')
    user = models.ForeignKey(User, default=None, on_delete=models.SET_DEFAULT)

    def __str__(self):
        return self.name


class Secret(models.Model):
    name = models.CharField(max_length=255, default="secret")
    value = models.CharField(max_length=255, default="")

    def __str__(self):
        return self.name

predictor/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    image = forms.FileField(
        label='Select an image',
        help_text='max. 2 megabytes'
    )

predictor/views.py
import os
import json
import pathlib
import requests
import gradio_client
from openai import OpenAI
from .models import Image, Secret
from django.db.models import Q
from .forms import ImageUploadForm
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
# Create your views here.

BASE_DIR = pathlib.Path(__file__).resolve().parent.parent
os.environ['OPENAI_API_KEY'] = Secret.objects.get(name='openai').value


def colored(r, g, b, text):
    return "\033[38;2;{};{};{}m{} \033[38;2;255;255;255m".format(r, g, b, text)


@login_required(login_url='/accounts/login')
def selectPlant(request):
    context = {}
    template_name = "predictor/select.html"
    return render(request=request, template_name=template_name, context=context)


def uploadImage(request, plant_name):
    if request.method == 'GET':
        form = ImageUploadForm()
        try:
            images = Image.objects.filter(
                Q(user=request.user) & Q(name=plant_name))
            context = {"form": form, "images": images,
                       "plant_name": plant_name}
            template_name = "predictor/predict.html"
        except Exception as e:
            context = {
                "error": e, 'message': 'An error occured while fetching your old images'}
            template_name = "plants/error.html"
            return render(request=request, template_name=template_name, context=context)
        return render(request=request, template_name=template_name, context=context)

    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = Image()
            image.image = form.cleaned_data['image']
            image.name = plant_name
            image.user = request.user
            image.save()
            return redirect('predictor:upload_image', plant_name)
    else:
        form = ImageUploadForm()
        images = Image.objects.filter(
            Q(user=request.user) & Q(name=plant_name))
        context = {"form": form, "images": images}
        template_name = "predictor/predict.html"
    return render(request=request, template_name=template_name, context=context)


def deleteImage(request, plant_name, id):
    image = get_object_or_404(Image, id=id)
    image.delete()
    return redirect("predictor:upload_image", plant_name)


def getGeneralPredictions(filename):
    API_URL = "https://api-inference.huggingface.co/models/linkanjarad/mobilenet_v2_1.0_224-plant-disease-identification"
    headers = {"Authorization": "Bearer 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"}

    with open(filename, "rb") as f:
        data = f.read()
    response = requests.post(API_URL, headers=headers, data=data)

    return response.json()


def getDescription(result):
    client = OpenAI()
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": f"In very brief simple word, what causes {result} and how can it be treated?"},
            ]
        )

        print(response)
        response = response.choices[0].message.content
    except Exception as e:
        response = 'Could not get description and treatment'
    return response


def getSpecificPrediction(filename, plant_name):
    api_endpoint = f"https://deepconclusions-{plant_name}.hf.space/"
    client = gradio_client.Client(api_endpoint)
    response = client.predict(
        # str (filepath or URL to image) in 'img' Image component
        filename,
        api_name="/predict"
    )

    with open(response, 'r') as file:
        result = json.load(file)

    return result['label']


def getPredictions(request, plant_name):
    context = {"plant_name": plant_name}

    # get image path
    try:
        images = Image.objects.filter(
            Q(user=request.user) & Q(name=plant_name))
        image_url = images[0].image.url
        context['image'] = images[0]
    except Image.DoesNotExist as e:
        context['error'] = e,
        context['message'] = 'The selected image does not exist, try uploading another image.'
        template_name = "plants/error.html"
        return render(request=request, template_name=template_name, context=context)

    except IndexError as e:
        context['error'] = e,
        context['message'] = 'You have not uploaded any images yet.'
        template_name = "plants/error.html"
        return render(request=request, template_name=template_name, context=context)

    # # Define the API endpoint
    try:
        if plant_name == 'general':
            result = getGeneralPredictions(f"{BASE_DIR}{image_url}")[0]
            description = getDescription(result['label'])
            context['description'] = description
            context['result'] = result['label']
        else:
            result = getSpecificPrediction(
                f"{BASE_DIR}{image_url}", plant_name)
            description = getDescription(result)
            context['description'] = description
            context['result'] = result

    except Exception as e:
        context['error'] = e,
        context['message'] = 'You can not make predictions now'
        template_name = "plants/error.html"
        return render(request=request, template_name=template_name, context=context)

    template_name = "predictor/result.html"
    return render(request=request, template_name=template_name, context=context)

predictor/templates/predictor/predict.html
{% extends 'plants/base.html' %} {% block content %} {% load static %}
<style>
  .image-upload-form input {
    border: 1px solid gray;
    border-radius: 0.25em;
  }

  .image-upload-form label {
    font-weight: medium;
  }
</style>
<section class="upload-section px-md-5 rounded fw-light">
  <div class="border rounded shadow p-md-5">
    <div class="row">
      <div class="col-12">
        <div class="guide p-3 pt-md-3 px-md-3">
          <h3 class="">Upload {{plant_name}} image for Disease Prediction</h3>
        </div>
      </div>

      <div class="form-container">
        <form
          action="{% url 'predictor:upload_image' plant_name %}"
          method="post"
          enctype="multipart/form-data"
          class="image-upload-form d-flex flex-md-row flex-column p-3"
        >
          {% csrf_token %} {{ form.as_p }}
          <div class="px-md-5">
            <input type="submit" value="Upload Image" class="btn btn-success" />
          </div>
        </form>
      </div>

      <div class="border rounded p-md-5 p-3">
        <figure class="d-flex image-container">
          {% if images %} {% for img in images %}
          <div class="px-3 image-box mb-3">
            <img
              src="{{img.image.url}}"
              class="align-middle rounded img-fluid"
              width="300"
              height="600"
            />
            <div class="image-label d-flex mt-1">
              <a
                href="/predictor/delete_image/{{plant_name}}/{{img.id}}"
                class="delete-btn btn btn-danger"
                >Remove</a
              >
            </div>
          </div>
          {% endfor %} {% else %}
          <div class="image-placeholder rounded text-center">
            Images will appear here
          </div>
          {% endif %}
        </figure>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-12 col-md-6 text-center">
        <div class="prediction-btn-container">
          <a
            href="{% url 'predictor:get_predictions' plant_name %}"
            class="btn btn-primary predict-btn btn-block"
          >
            Get Predictions
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

predictor/templates/predictor/result.html
{% extends 'plants/base.html' %} {% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="mb-4 text-capitalize">
        {{plant_name}} Disease Prediction Results
      </h2>
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Image</h5>
          <img
            src="{{ image.image.url }}"
            class="img-fluid mb-3"
            alt="plant image"
          />
        </div>
      </div>
      {% if result %}
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title fw-bold">Prediction</h5>
          <p class="card-text">
            The predicted class is <strong>{{ result }}</strong>
          </p>
          <p class="card-text">{{ description|safe }}</p>
        </div>
      </div>
      {% else %}
      <div class="alert alert-danger" role="alert">{{ error_message }}</div>
      {% endif %}
      <div class="mt-4">
        <a
          href="{% url 'predictor:upload_image' plant_name %}"
          class="btn btn-primary"
          >Try Again</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

predictor/templates/predictor/select.html
{% extends 'plants/base.html' %} {% block content %}
{% load static%}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <a href="upload_image/tomato" class="col text-decoration-none text-dark">
        <div class="card shadow-sm">
          <img
            src = "{% static 'deep/tomato_leaf.JPG' %}"
            class="bd-placeholder-img card-img-top"
            width="100%"
            height="225"
            xmlns="http://www.w3.org/2000/svg"
            role="img"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
          >
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>
          <div class="card-body">
            <h2>Tomato</h2>
            <p class="card-text">
              Analyze your tomato plants for disease using our AI-powered
              platform.
            </p>
          </div>
        </div>
      </a>
      <a href="upload_image/corn" class="col text-decoration-none text-dark">
        <div class="card shadow-sm">
          <img
            src = "{% static 'deep/corn_leaf.jpg' %}"
            class="bd-placeholder-img card-img-top  "
            width="100%"
            height="225"
            xmlns="http://www.w3.org/2000/svg"
            role="img"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
          >
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>
          <div class="card-body">
            <h2>Corn</h2>
            <p class="card-text">
              Analyze your Corn plants for disease using our AI-powered
              platform.
            </p>
          </div>
        </div>
      </a>
      <a href="upload_image/general" class="col text-decoration-none text-dark">
        <div class="card shadow-sm">
          <img
            src = "https://media.springernature.com/m685/springer-static/image/art%3A10.1007%2Fs11277-021-09054-2/MediaObjects/11277_2021_9054_Fig6_HTML.png"
            class="bd-placeholder-img card-img-top"
            width="100%"
            height="225"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="xMidYMid slice"
            focusable="false"
          >
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>
          <div class="card-body">
            <h2>General</h2>
            <p class="card-text">
              Analyze any plants for disease using our AI-powered
              platform.
            </p>
          </div>
        </div>
      </a
    </div>
  </div>
</div>
{% endblock content %}