accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup", views.signup_view, name="signup"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

plants/urls.py
from . import views
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "plants"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("pricing", views.pricing, name="pricing"),
    path("support", views.support, name="support"),
    path("careers", views.careers, name="careers"),
    path("videos", views.videos, name="videos"),
    path(route='faqs', view=views.faqs, name='faqs'),
    path('accounts/', include('accounts.urls')),
    path('predictor/', include('predictor.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "predictor"

urlpatterns = [
    path("select_plant", views.selectPlant, name="select_plant"),
    path("upload_image/<str:plant_name>",
         views.uploadImage, name="upload_image"),
    # path("get_single_prediction/<int:id>",
    #      views.getSinglePrediction, name="get_single_prediction"),
    path("get_predictions/<str:plant_name>", views.getPredictions, name="get_predictions"),
    path("delete_image/<str:plant_name>/<int:id>", views.deleteImage, name="delete_image")
]

plants/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'plants/home.html')


def about(request):
    return render(request, 'plants/about.html')


def pricing(request):
    return render(request, 'plants/pricing.html')


def support(request):
    return render(request, "plants/support.html")


def careers(request):
    return render(request, "plants/careers.html")


def videos(request):
    return render(request, "plants/videos.html")


def faqs(request):
    context = {}
    return render(request=request, template_name="plants/faqs.html", context=context)

plants/templates/plants/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,600;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Anek+Telugu&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/duotone.css"
      integrity="sha384-R3QzTxyukP03CMqKFe0ssp5wUvBPEyy9ZspCB+Y01fEjhMwcXixTyeot+S40+AjZ"
      crossorigin="anonymous"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'css/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'css/aos/aos.css" rel="stylesheet' %}" />

    <link
      rel="shortcut icon"
      href="{% static '/deep/logo.png' %}"
      type="image/x-icon"
    />

    <title>DC plant disease predcitor</title>
    <style>
      nav {
        background: #fff;
      }

      h1,
      h2,
      h3,
      h4,
      h5 {
        font-family: "Anek Telugu";
      }
    </style>
  </head>
  <body class="" style="font-family: Poppins">
    <header>
      <nav
        class="p-3 navbar navbar-expand-lg rounded"
        aria-label="Thirteenth navbar example"
      >
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarsExample11"
            aria-controls="navbarsExample11"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div
            class="px-5 collapse navbar-collapse d-lg-flex"
            id="navbarsExample11"
          >
            <a class="navbar-brand col-lg-3 me-0" href="/"
              ><h2 class="fw-bold">
                <span>
                  <img
                    src="{% static '/deep/logo.png' %}"
                    width="100"
                    class="img-fluid"
                  /> </span
                >Lens
              </h2></a
            >
            <ul class="navbar-nav col-lg-6 justify-content-lg-center">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'predictor:select_plant'%}"
                  >Predict</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/pricing">Pricing</a>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="/about"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                  >About</a
                >
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="/about">About Us</a></li>
                  <li><a class="dropdown-item" href="/careers">Careers</a></li>
                  <li><a class="dropdown-item" href="/faqs">FAQs</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                  >Resources</a
                >
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="/videos">Videos</a></li>
                  <li>
                    <a
                      class="dropdown-item"
                      href="https://deepconclusions.com/blogs"
                      >Blogs</a
                    >
                  </li>
                  <!-- <li><a class="dropdown-item" href="#">Community</a></li> -->
                  <!-- <li><a class="dropdown-item" href="/support">Support</a></li> -->
                </ul>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <form action="/accounts/logout" method="POST" class="">
              {%csrf_token%}
              <a href="/about" class="btn border-success text-success"
                >Contact us</a
              >
              <button
                type="submit"
                class="btn btn-danger text-weight-bold"
                value="Let me out"
              >
                Logout
              </button>
              {% else %}
              <a href="{% url 'accounts:login'%}" class="btn btn-primary"
                >Login</a
              >
              <a
                href="{% url 'accounts:login'%}"
                class="btn mx-md-2 btn-warning"
                >Start For Free</a
              >
              {% endif %}
            </form>
          </div>
        </div>
      </nav>
    </header>
    <div class="mt-5">{% block content %}{% endblock content %}</div>
    <script src=""></script>
    <div class="bg-light">
      <footer class="p-5">
        <div class="row">
          <div class="col-6 col-md-2 mb-3">
            <h5>Company</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="about" class="nav-link p-0 text-muted">About Us</a>
              </li>
              <li class="nav-item mb-2">
                <a href="careers" class="nav-link p-0 text-muted">Careers</a>
              </li>
              <li class="nav-item mb-2">
                <a href="/pricing" class="nav-link p-0 text-muted">Pricing</a>
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">FAQs</a>
              </li>
            </ul>
          </div>

          <div class="col-6 col-md-2 mb-3">
            <h5>Resources</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="/videos" class="nav-link p-0 text-muted">Video</a>
              </li>
              <li class="nav-item mb-2">
                <a
                  href="https://deepconclusions.com/blogs"
                  class="nav-link p-0 text-muted"
                  >Blogs</a
                >
              </li>
              <!-- <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Community</a>
              </li>
              <li class="nav-item mb-2">
                <a href="/support" class="nav-link p-0 text-muted">Support</a>
              </li> -->
            </ul>
          </div>

          <div class="col-6 col-md-2 mb-3">
            <h5>Product</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="/" class="nav-link p-0 text-muted">DeepConcLens</a>
              </li>
              <li class="nav-item mb-2">
                <a href="/benefits" class="nav-link p-0 text-muted">Benefits</a>
              </li>
              <li class="nav-item mb-2">
                <a href="/why-ai" class="nav-link p-0 text-muted">Why Ai</a>
              </li>
            </ul>
          </div>

          <div class="col-md-5 offset-md-1 mb-3">
            <form>
              <h5>Subscribe to our newsletter</h5>
              <p>Monthly digest of what's new and exciting from us.</p>
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                <label for="newsletter1" class="visually-hidden"
                  >Email address</label
                >
                <input
                  id="newsletter1"
                  type="text"
                  class="form-control"
                  placeholder="Email address"
                />
                <button class="btn btn-primary" type="button">Subscribe</button>
              </div>
            </form>
          </div>
        </div>

        <div
          class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top"
        >
          <p>&copy; 2023 Deep Conclusions. All rights reserved.</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#twitter" /></svg
              ></a>
            </li>
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#instagram"></use>
                </svg>
              </a>
            </li>
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#facebook" /></svg
              ></a>
            </li>
          </ul>
        </div>
      </footer>
    </div>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

plants/templates/plants/error.html
{% extends 'plants/base.html' %} {% block content %} {% load static %}
<div class="flex justify-content-center pb-5">
  <div class="p-5 mx-5 border rounded shadow" style="background: lightyellow">
    <h2 class="fw-bold">A problem occured!</h2>
    <p><span class="fw-semibold">Error:</span> {{ error }}</p>
    <p><span class="fw-semibold">Message:</span> {{ message }}</p>
    <input
      class="btn btn-primary"
      type="button"
      value="Go Back"
      onClick="javascript:history.go(-1);"
    />
  </div>
</div>
{% endblock content %}

plants/templates/plants/faqs.html
{% extends 'plants/base.html' %} {% block content %} {% load static %}
<h1>FAQs</h1>
{% endblock content%}

plants/templates/plants/home.html
{% extends 'plants/base.html' %} {% block content %}
{% load static %}
<div class="px-4 pt-5 my-5 text-center border-bottom">
  <h1 class="fw-bold">Deep Conc-Lens, An Easy Way</h1>
  <h1 class="fw-bold">to Detect Plant Diseases</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Our system has models that have been trained over a large range of
      datasets to ensure accuracy and optimized for speed.
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <a
        href="{% url 'predictor:select_plant'%}"
        class="btn btn-warning px-4 me-sm-3"
      >
        Start For Free
      </a>
    </div>
  </div>
  <div class="">
    <div class="container px-5">
      <img
        src="{% static 'deep/DeepConcLens3.png' %}"
        class="img-fluid border rounded-3 shadow-lg mb-4"
        alt="deep conclusions working structure"
        width="900"
        height="700"
        loading="lazy"
      />
    </div>
  </div>
</div>
<div class=""></div>
<section class="px-md-5 px-2 pt-5 my-5 border-bottom fw-light">
  <div class="m-5 row d-flex justify-content-between">
    <main class="col-md-6 col-12">
      <h4 class="fw-bold">GET STARTED IN MINUTES</h4>
      <h2>Detect diseases in plants, fast, easily</h2>
      <p>
        Our intuitive software platform enables anyone to easily detect diseases
        in plants, without any prior AI knowledge. With just a few clicks, you
        can upload images of your plants and get fast, accurate results in
        minutes. Our AI-powered algorithms analyze the images to identify signs
        of disease, allowing you to quickly take action and protect your crops.
        This solution is both affordable and user-friendly, making it accessible
        to farmers and plant enthusiasts of all levels. Don't let plant diseases
        go undetected - try our platform today and start detecting with ease.
      </p>
    </main>
    <aside class="col-md-3 col-12">
      <img
        src="{% static 'deep/black_rot.JPG' %}"
        width="100%"
        class="img-fluid border shadow rounded"
      />
    </aside>
  </div>
</section>
<section
  class="px-md-5 px-2 pt-5 my-5 border-bottom text-light fw-light bg-success"
>
  <div class="m-5 row d-flex justify-content-between">
    <aside class="col-md-3 col-12">
      <img src="{% static 'deep/tomato_leaf.JPG' %}" width="100%" class="rounded" />
    </aside>
    <main class="col-md-6 col-12 pt-5">
      <h4 class="fw-bold">HIGER SPEED, GREATER ACCURACY</h4>
      <h2>Artificial intelligence maximises speed and accuracy</h2>
      <p>
        Artificial intelligence (AI) used in our systems has the ability to
        significantly improve disease detection by maximizing both speed and
        accuracy. Using advanced algorithms and machine learning techniques, AI
        can quickly analyze large amounts of data, identify patterns and
        anomalies, and provide highly accurate diagnoses in real-time.
      </p>
    </main>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="text-center">How It Works</h1>
      <p class="fw-light text-center">
        Check out how Deep Conc-Lens makes plant disease detection super easy
        and delivers accurate predictions faster.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button
              class="accordion-button"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseOne"
              aria-expanded="true"
              aria-controls="collapseOne"
            >
              Step 1
            </button>
          </h2>
          <div
            id="collapseOne"
            class="accordion-collapse collapse show"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionExample"
          >
            <div class="p-md-5 m-md-5 accordion-body d-flex row">
              <div class="col-md-6">
                <h2>Select plant to detect disease from</h2>
                <p>
                  To use our disease detection system, the first step is to
                  select the plant you want to analyze. We offer a range of
                  models for different plants, including corn, pepper, peach,
                  and tomatoes, all powered by our advanced AI algorithms.
                  Simply choose the plant you want to analyze from our list, and
                  our system will automatically apply the appropriate model to
                  the images you upload.
                </p>
              </div>
              <div class="col-md-6">
                <img
                  src="{% static 'deep/select_plant.png' %}"
                  class="img-fluid border rounded-3 shadow-lg mb-4"
                  alt="Example image"
                  width="500"
                  height="300"
                  loading="lazy"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button
              class="accordion-button collapsed"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseTwo"
              aria-expanded="false"
              aria-controls="collapseTwo"
            >
              Step 2
            </button>
          </h2>
          <div
            id="collapseTwo"
            class="accordion-collapse collapse"
            aria-labelledby="headingTwo"
            data-bs-parent="#accordionExample"
          >
          <div class="p-md-5 m-md-5 accordion-body d-flex row">
            <div class="col-md-6">
                <h2>Select leaf images</h2>
                <p>
                  Choose leaf images from which you want to detect the disease
                </p>
                <p>
                  Notice that when you change your mind, you can remove the
                  images
                </p>
                <p>
                  Click "Get Predictions" button to get the prediction of the
                  diseases in your plant
                </p>
              </div>
              <div class="col-md-6">
                <img
                  src="{% static 'deep/select_images.png'%}"
                  class="img-fluid border rounded-3 shadow-lg mb-4"
                  alt="Example image"
                  width="500"
                  height="300"
                  loading="lazy"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button
              class="accordion-button collapsed"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseThree"
              aria-expanded="false"
              aria-controls="collapseThree"
            >
              Step 3
            </button>
          </h2>
          <div
            id="collapseThree"
            class="accordion-collapse collapse"
            aria-labelledby="headingThree"
            data-bs-parent="#accordionExample"
          >
          <div class="p-md-5 m-md-5 accordion-body d-flex row">
            <div class="col-md-6">
                <h2>View Results</h2>
                <p>
                  After a few seconds, you should be redirected to the "Results"
                  page from which your results will be displayed
                </p>
                <p>
                  Notice that you can run another test with the same or
                  different image to confirm the prediction
                </p>
              </div>
              <div class="col-md-6">
                <img
                  src="{% static 'deep/results.png'%}"
                  class="img-fluid border rounded-3 shadow-lg mb-4"
                  alt="Example image"
                  width="500"
                  height="300"
                  loading="lazy"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="px-4 pt-5 my-5 border-bottom text-light fw-light bg-success">
  <div class="p-md-5 m-5 row d-flex justify-content-between">
    <h2 class="col-6">See How Easy Plant Disease Detection Can Be</h2>
    <div class="col-6 d-flex flex-column align-content-center">
      <p>Detect deases in your plants with out technology</p>
      <a href="" class="d-inline-block text-center btn btn-warning">
        Start For Free
      </a>
    </div>
  </div>
</section>
{% endblock content %}

plants/templates/plants/pricing.html
{% extends 'plants/base.html' %} {% block content %}
{% load static %}
<div>
  <h3 class="fw-bold text-center">PLANS AND PRICING</h3>
  <h1 class="text-center text-success">Choose the plan for you and your team</h1>
</div>
<main class="p-5">
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Free</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Up to 5 projects</li>
              <li>Max 10 images per project</li>
              <li>Starter Model</li>
              <li>Community Support</li>
            </ul>
            <a  href = "{%url 'predictor:select_plant'%}" class="w-100 btn btn-lg btn-outline-success">Start For Free</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Up to 20 projects</li>
              <li>Max 100 images per project</li>
              <li>Intermediate model</li>
              <li>Help center access</li>
            </ul>
            <a  href = "{%url 'predictor:select_plant'%}" class="w-100 btn btn-lg btn-success">Start For Free</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-success">
          <div class="card-header py-3 text-bg-success border-success">
            <h4 class="my-0 fw-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Large image support</li>
              <li>Overdraft exception</li>
              <li>Advanced and Dedicated model</li>
              <li>Phone and email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-success">Contact us</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Free</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Public</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Private</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div>
  </main>
  <div class="p-5 row justify-self-center">
    <div class="col-12">
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button
              class="accordion-button"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseOne"
              aria-expanded="true"
              aria-controls="collapseOne"
            >
              What are credits?
            </button>
          </h2>
          <div
            id="collapseOne"
            class="accordion-collapse collapse show"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionExample"
          >
            <div class="p-md-5 accordion-body d-flex row">
              <div class="">
                <p>
                  Credits are a form of currency on the DeepConc-Lens platform. You spend credits on models to make predictions.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button
              class="accordion-button collapsed"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseTwo"
              aria-expanded="false"
              aria-controls="collapseTwo"
            >
              What if I go over my alloted credits?
            </button>
          </h2>
          <div
            id="collapseTwo"
            class="accordion-collapse collapse"
            aria-labelledby="headingTwo"
            data-bs-parent="#accordionExample"
          >
          <div class="p-md-5 accordion-body d-flex row">
            <div class="">
                <p>
                  By default, your organization will be upgraded to the next credit package within the tier. If you prefer the credit limit to be enforced, you can turn off this setting. You can also downgrade to a lower credit package whenever you would like to.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingThree">
            <button
              class="accordion-button collapsed"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseThree"
              aria-expanded="false"
              aria-controls="collapseThree"
            >
            Do credits rollover at the end of the billing cycle?
            </button>
          </h2>
          <div
            id="collapseThree"
            class="accordion-collapse collapse"
            aria-labelledby="headingThree"
            data-bs-parent="#accordionExample"
          >
          <div class="p-md-5 accordion-body d-flex row">
            <div class="">
                <h2>View Results</h2>
                <p>
                  Credits do not rollover for Free and Pro tiers and will reset each month.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="px-4 pt-5 my-5 border-bottom text-light fw-light bg-success">
    <div class="p-md-5 m-5 row d-flex justify-content-between">
      <h2 class="col-6">See How Easy Plant Disease Detection Can Be</h2>
      <div class="col-6 d-flex flex-column align-content-center">
        <p>Detect deases in your plants with out technology</p>
        <a href="" class="d-inline-block text-center btn btn-warning">
          Start For Free
        </a>
      </div>
    </div>
  </div>
  {% endblock content %}

plants/templates/plants/videos.html
{% extends 'plants/base.html' %} {% block content %}
{% load static %}
<div>
    <h1>
        Videos
    </h1>
</div>
{% endblock content %}